name: Makefile CI

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '19 7 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make

