on: workflow_dispatch
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make

    # Deploy to local repo
    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: data_build
        FOLDER: tools/data_build
        GITHUB_TOKEN: ${{ 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 }}